from News.models import *


user1 = User.objects.create_user('Петр')
user2 = User.objects.create_user('Иван')
user3 = User.objects.create_user('Сергей')
Author1 = Author.objects.create(authorUser=user1)
Author2 = Author.objects.create(authorUser=user2)
Category.objects.create(name='Space')
Category.objects.create(name='IT')
Category.objects.create(name='Sport')
Category.objects.create(name='Policy')
Post.objects.create(author_id=1, title='Заголовок новости 1', text='Текст новости 1, про непонятно что', categoryType='AR')
Post.objects.create(author_id=2, title='Заголовок новости 2', text='Текст новости 2, про IT', categoryType='AR')
Post.objects.create(author_id=2, title='Заголовок новости 3', text='Текст новости 3, про Sport', categoryType='NW')
Post.objects.create(author_id=1, title='Заголовок новости 4', text='Текст новости 4, Футбол ', categoryType='NW')
Post.objects.create(author_id=1, title='Заголовок новости 5', text='Текст новости 5, Космос. Найдена Raxxla ', categoryType='NW')
Post.objects.create(author_id=1, title='Заголовок новости 6', text='Текст новости 6, Космос. Таргоиды атакуют мирное население ', categoryType='AR')
post1 = Post.objects.get(pk=1)
post2 = Post.objects.get(pk=2)
post3 = Post.objects.get(pk=3)
post4 = Post.objects.get(pk=4)
post5 = Post.objects.get(pk=5)
post6 = Post.objects.get(pk=6)
category1 = Category.objects.get(name='Sport')
category2 = Category.objects.get(name='Space')
category3 = Category.objects.get(name='IT')
post1.postCategory.add(category1, category2, category3)
post2.postCategory.add(category2)
post3.postCategory.add(category3)
post4.postCategory.add(category3, category2, category1)
post5.postCategory.add(category1)
post5.postCategory.add(category1)
Comment.objects.create(commentUser=user3, commentPost=post1, text='Знатная скотина, мех, шкварки, удовольствие')
Comment.objects.create(commentUser=user2, commentPost=post1, text='А о чем эта новость?')
Comment.objects.create(commentUser=user1, commentPost=post1, text='Новость не читал, но осуждаю')
Comment.objects.create(commentUser=user1, commentPost=post5, text='Неужели её нашли?')
Comment.objects.create(commentUser=user2, commentPost=post5, text='Пора отправлять на Ганимед за фейковые новости')
Comment.objects.create(commentUser=user3, commentPost=post6, text='А вы с ними еще в футбол играть хотели')
Comment.objects.create(commentUser=user1, commentPost=post6, text='Все не так однозначно, они просто так видят мир')
Comment.objects.create(commentUser=user2, commentPost=post2, text='Невидимые технологии на страже кавалерии')
Comment.objects.create(commentUser=user3, commentPost=post2, text='Лошадь не прошла через пакетный фильтр благодаря СОРМ')
Comment.objects.create(commentUser=user1, commentPost=post3, text='Спортивные ребята как всегда обыграли неспортивных ребят')
Comment.objects.create(commentUser=user2, commentPost=post3, text='ЗОЖ обман и провокация, занимайтесь НВП и будете здоровы')
Comment.objects.create(commentUser=user2, commentPost=post4, text='Штанга обыграла вратаря')
Comment.objects.create(commentUser=user3, commentPost=post4, text='На юге Москвы сгорел склад с огнетушителями')
post1.like()
post2.dislike()
Author1.update_rating()
Author.objects.get(authorUser_id=1).update_rating()
Author.objects.get(authorUser_id=2).update_rating()
Author.objects.get(authorUser=User.objects.get(username='Петр')).update_rating()
a1 = Author.objects.get(authorUser_id=1)
a2 = Author.objects.get(authorUser_id=2)
a1.ratingAuthor
bestAuthor = Author.objects.all().order_by('-ratingAuthor').values('authorUser','ratingAuthor')[0]
bestPost = Post.objects.all().order_by('-rating').values('author','rating')[0]