# Generated by Django 4.2.4 on 2023-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('News', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('categories', models.ManyToManyField(to='News.category')),
            ],
        ),
    ]
