# Generated by Django 4.2.4 on 2023-08-29 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('News', '0003_category_subscribers'),
        ('News', '0005_category_subscribers'),
    ]

    operations = [
    ]
