# Generated by Django 4.2.4 on 2023-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0006_merge_20230829_1233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
