# Generated by Django 4.2.6 on 2023-10-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0008_alter_subscriber_options_remove_subscriber_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en_us",
            field=models.CharField(
                help_text="название категории", max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                help_text="название категории", max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="text_en_us",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en_us",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="название категории", max_length=64, unique=True
            ),
        ),
    ]
